version: 2

jobs:
  build:
    docker:
      - image: typelogic/circleci-android:latest
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          name: "Build debug/release and run tests"
          command: |
              if test -f "build.sh"; then
                  ./build.sh
              fi
      - store_artifacts:
          path: /home/circleci/project/build/release/lib/src/libidpasslite.so
          destination: libidpasslite.so
      - store_artifacts:
          path: /home/circleci/project/build/html.tar.gzip
          destination: html.tar.gzip
      - store_test_results:
          path: /home/circleci/project/build/reports.xml
