version: 2

jobs:
  build:
    docker:
      - image: newlogic42/circleci-android:latest
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          name: "Initial"
          command: |
              if test -f "build.sh"; then
                  ./build.sh
              fi
      - store_artifacts:
          path: /home/circleci/project/build/idpass/jniLibs.tar.bz2
          destination: jniLibs.tar.bz2
      - store_artifacts:
          path: /home/circleci/project/build/idpass/jniLibs.tar.bz2.md5sum
          destination: jniLibs.tar.bz2.md5sum
